#!/usr/bin/env python3

import logging
import argparse
import dryable
from qcrepocleaner.Ccdb import Ccdb
from qcrepocleaner.binUtils import prepare_main_logger
import re


def parse_args():
    """Parse the arguments passed to the script."""
    logging.info("Parsing arguments")
    parser = argparse.ArgumentParser(description='Move all objects in path to new-path')
    parser.add_argument('--url', dest='url', action='store', help='URL of the CCDB, with http[s]://', required=True)
    parser.add_argument('--log-level', dest='log_level', action='store', default="20",
                        help='Log level (CRITICAL->50, ERROR->40, WARNING->30, INFO->20,DEBUG->10)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Dry run, no actual deletion nor modification to the CCDB.')
    parser.add_argument('--path', dest='path', action='store', default="",
                        help='Origin path without initial slash and without .* at the end (e.g. qc/TST/MO/Bob).', required=True)
    parser.add_argument('--one-by-one', action='store_true', help='Ask confirmation for each deletion')
    args = parser.parse_args()
    dryable.set(args.dry_run)
    logging.info(args)
    return args


def run(args):
    ccdb = Ccdb(args.url)

    nb_updated = 0
    # we have to make sure we take all objects in the subfolders --> we add `/.*` at the end
    versions = ccdb.getVersionsList(args.path + "/.*", "", "")
    # we also want to have all the versions at the root
    versions += ccdb.getVersionsList(args.path, "", "")

    logging.debug("Here are the objects that are going to be updated: ")
    for v in versions:
        logging.info(v)
    logging.info(f"Number of items: {len(versions)}")

    logging.warning("****** ARE YOU ABSOLUTELY SURE YOU WANT TO CONTINUE ? ******")
    answer = input("Yes/No \n  ")
    if answer.lower() not in ["y", "yes"]:
        exit(0)

    # TODO: get a map with run number -> run type
    runs_mapping = {}

    for v in versions:
        run_number = v.metadata.get("RunNumber")
        if run_number is None:
            logging.warning(f"Could not find metadata RunNumber for version {v}")
            continue

        run_type = runs_mapping.get(run_number)
        if run_type is None:
            logging.warning(f"Could not find run type for run number {run_number}")
            continue

        metadata = {"RunType", run_type}

        logging.debug(f"Ready to update {v} with run type {run_type}")
        if args.one_by_one:
            answer = input("  Continue? y/n\n  ")
            if answer.lower() in ["y", "yes"]:
                ccdb.updateMetadata(v, metadata)
                nb_updated += 1
            elif answer.lower() in ["n", "no"]:
                logging.info("   skipping")
            else:
                logging.error("   wrong input, skipping")
        else:
            ccdb.updateMetadata(v, metadata)
            nb_updated += 1

    logging.info(f"Updated items: {nb_moved}")

# ****************
# We start here !
# ****************

def main():
    prepare_main_logger()

    # Parse arguments
    args = parse_args()
    logging.getLogger().setLevel(int(args.log_level))

    run(args)


if __name__ == "__main__":
    main()
