{
 "title": "QCDB benchmark",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Benchmarks runs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "ccdb_benchmark",
     "select": [
      [
       { "params": [ "number_tasks" ], "type": "field" }
      ],
      [
       { "params": [ "number_objects" ], "type": "field" }
      ],
      [
       { "params": [ "size_objects" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Object rate per task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ccdb_benchmark_objects_sent",
     "select": [
      [
       { "params": [ "value_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "taskName", "operator": "=", "value": "benchmarkTask_0" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated object rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "ccdb_benchmark_objects_sent",
     "select": [
      [
       { "params": [ "value_rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time (ms) to publish 1 object",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ccdb_benchmark_store_duration_for_one_object_ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "taskName", "operator": "=", "value": "benchmarkTask_0" }
     ]
    }
   ]
  },
  {
   "title": "Average time (ms) to publish 1 object",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ccdb_benchmark_store_duration_for_one_object_ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "taskName", "operator": "=", "value": "benchmarkTask_0" }
     ]
    }
   ]
  }
 ]
}